//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecommendSystemContentBased.Models.TaiplaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class food_ingredient
    {
        public int id { get; set; }
        public int food_id { get; set; }
        public string description { get; set; }
        public string unit { get; set; }
        public string weight { get; set; }
        public string thumbnail { get; set; }
        public string code { get; set; }
        public int legend_status { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    }
}
