//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecommendSystemContentBased.Models.TaiplaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class history_search
    {
        public int id { get; set; }
        public string client_id { get; set; }
        public string device_id { get; set; }
        public string search_text { get; set; }
        public string condition { get; set; }
        public int deleted { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    }
}
