//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecommendSystemContentBased.Models.TaiplaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class restaurant_menu
    {
        public int menu_id { get; set; }
        public int res_id { get; set; }
        public int country_id { get; set; }
        public int culture_id { get; set; }
        public string name_th { get; set; }
        public string name_en { get; set; }
        public string description { get; set; }
        public string cooking_food { get; set; }
        public string dietetic_food { get; set; }
        public string code { get; set; }
        public double price { get; set; }
        public string thumbnail { get; set; }
        public int viewer { get; set; }
        public int legend_status { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    }
}
