//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecommendSystemContentBased.Models.TaiplaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class restaurant
    {
        public int res_id { get; set; }
        public int user_id { get; set; }
        public Nullable<int> owner_id { get; set; }
        public int country_id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string province { get; set; }
        public string map { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        public string website { get; set; }
        public string facebook { get; set; }
        public string line { get; set; }
        public string open_time { get; set; }
        public string phone { get; set; }
        public string tags { get; set; }
        public int car_park { get; set; }
        public string thumbnail { get; set; }
        public int viewer { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    }
}
