//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecommendSystemContentBased.Models.TaiplaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_device
    {
        public int id { get; set; }
        public string device_id { get; set; }
        public string device_type { get; set; }
        public string token { get; set; }
        public string client_id { get; set; }
        public System.DateTime expired { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    }
}
